name: Angular Package

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build:core
      - run: npm run build:kit
      - run: npm run build:layout
      - name: Upload distribution folders
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./dist/kbm/core
            ./dist/kbm/kit
            ./dist/kbm/layout

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download distribution folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish core library
        with:
          name: dist
          path: ./dist/kbm/core
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
